symfony-master2/src/Entity/Video.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VideoRepository")
 */
class Video
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Link;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $NomLink;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="videos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    public function getId()
    {
        return $this->id;
    }

    public function getLink(): ?string
    {
        return $this->Link;
    }

    public function setLink(string $Link): self
    {
        $this->Link = $Link;

        return $this;
    }

    public function getNomLink(): ?string
    {
        return $this->NomLink;
    }

    public function setNomLink(string $NomLink): self
    {
        $this->NomLink = $NomLink;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }
}

symfony-master2/src/Form/VideoType.php
<?php

namespace App\Form;

use App\Entity\Video;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VideoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Link')
            ->add('NomLink')
            ->add('Description', TextareaType::class)
            
            ->add('submit',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Video::class,
        ]);
    }
}

symfony-master2/src/Controller/VideoController.php
<?php

namespace App\Controller;

use App\Entity\Video;
use App\Form\VideoType;
use App\Repository\VideoRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
class VideoController extends Controller
{
    /**
     * @Route("/", name="video")
     */
    public function index(Request $request, VideoRepository $videoRepository)
    {

        $video = new Video();
        

        $videos = $videoRepository->findAll();

        return $this->render('video/index.html.twig', array(

           'video'=>$videos
            
        )
        );
    }
     /**
     * @Route("/video/remove/{id}", name="video_remove")
     * @ParamConverter("video", options={"mapping"={"id"="id"}})
     */

    public function remove(Video $video, EntityManagerInterface $entityManager){

        $entityManager->remove($video);
        $entityManager->flush();
        return $this->redirectToRoute('home');

    }

    /**
     * @Route("/video/{id}", name="video_detail")
     * @ParamConverter("video", options={"mapping"={"id"="id"}})
     */

    public function detailVideo($id){

        //$video = new Video();
        //$videos = $videoRepository->findAll();
        $videos = $this->getDoctrine()->getRepository(Video::class)->find($id);

         if (!$videos) {
        throw $this->createNotFoundException('No video found for id '.$id);
    }

    
        return $this->render('video/index_detail.html.twig', array(

           'video'=>$videos
            
        )
        );

    }
}

symfony-master2/templates/video/detail.html.twig
{% extends 'base.html.twig' %}
{% block title %}Hello {% endblock %}

{% block body %}


<div >
            <div class="inner">
              <h1>{{ video.nomlink }}</h1>
              <span class="image main"><img src="images/pic13.jpg" alt="" /></span>
              <p>{{ video.nomlink }}</p>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis dapibus rutrum facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tristique libero eu nibh porttitor fermentum. Nullam venenatis erat id vehicula viverra. Nunc ultrices eros ut ultricies condimentum. Mauris risus lacus, blandit sit amet venenatis non, bibendum vitae dolor. Nunc lorem mauris, fringilla in aliquam at, euismod in lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In non lorem sit amet elit placerat maximus. Pellentesque aliquam maximus risus, vel venenatis mauris vehicula hendrerit.</p>
              <p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis dolor imperdiet dolor mattis sagittis. Praesent rutrum sem diam, vitae egestas enim auctor sit amet. Pellentesque leo mauris, consectetur id ipsum sit amet, fersapien risus, commodo eget turpis at, elementum convallis elit. Pellentesque enim turpis, hendrerit tristique lorem ipsum dolor.</p>
            </div>
          </div>

 <br>
  
    {% endblock %}
    

symfony-master2/templates/video/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Hello {% endblock %}

{% block body %}



<section class="tiles">
  {% for videos in video %}
              
 

                <article class="style6" id="{{ videos.nomlink }}">
                  <span class="image">
                     <iframe class="block" width="450" height="260"  src="{{ videos.link | replace({'watch?v=': 'embed/'}) }}" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                  </span>
                  <a href="{{ path('video_detail', {'id': videos.id}) }}">
                    <h2>{{ videos.nomlink }}</h2>
                    <div class="content">
                     <p>{{ videos.nomlink }}</p>
                    </div>
                  </a>
                </article>
                 {% endfor %}
  </section>
 <br>
  
    {% endblock %}

symfony-master2/templates/video/index_detail.html.twig
{% extends 'base.html.twig' %}
{% block title %}Detail Video {% endblock %}

{% block body %}


    <section class="tiles">

  
  
              
 

                <article class="style6" id="{{ video.nomlink }}">
                  <a href="{{ path('video_detail', {'id': video.id}) }}"><h1>{{ video.nomlink }}</h1></a>
                  
               <span class="image">
                     <iframe class="block" width="450" height="260"  src="{{ video.link | replace({'watch?v=': 'embed/'}) }}" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe> </a>
                  </span>
              <p>{{ video.nomlink }}</p>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis dapibus rutrum facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tristique libero eu nibh porttitor fermentum. Nullam venenatis erat id vehicula viverra. Nunc ultrices eros ut ultricies condimentum. Mauris risus lacus, blandit sit amet venenatis non, bibendum vitae dolor. Nunc lorem mauris, fringilla in aliquam at, euismod in lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In non lorem sit amet elit placerat maximus. Pellentesque aliquam maximus risus, vel venenatis mauris vehicula hendrerit.</p>
              <p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis dolor imperdiet dolor mattis sagittis. Praesent rutrum sem diam, vitae egestas enim auctor sit amet. Pellentesque leo mauris, consectetur id ipsum sit amet, fersapien risus, commodo eget turpis at, elementum convallis elit. Pellentesque enim turpis, hendrerit tristique lorem ipsum dolor.</p>
            </div>
                </article>
                 
  </section>
 <br>
  
    {% endblock %}